package les.projects.consultation_scheduling_program.Components;

import javafx.scene.control.Button;
import javafx.scene.layout.GridPane;
import les.projects.consultation_scheduling_program.Enums.Styles;

/**
 * This class extends the JavaFX Button and formats it.
 *
 * @author Leslie C. Bomar 3rd
 * @version 1.0
 */
public class ButtonStandard extends Button {

    /**
     * This constructor instantiates a JavaFX button for use in a GridPane.
     * @param s String to display on the button.
     * @param c If applying to a GridPane, you can specify the column here.
     * @param r If applying to a GridPane, you can specify the row here.
     */
    public ButtonStandard(String s, int c, int r) {
        GridPane.setConstraints(this, c, r);
        this.styleIt(s);
    }

    /**
     * This constructor instantiates a JavaFX button.
     * @param s String to display on the button.
     */
    public ButtonStandard(String s) {
        this.styleIt(s);
    }

    /**
     * This method applies styling to the button during certain mouse events. Four lambdas were used here to handle
     * the events generated by the OnMouse events. Four lambdas were used here to prevent the need to use the
     * addListener method (which is more verbose) and eliminates referencing private methods, making the code
     * more readable.
     */
    private void addMouseEffects() {
        this.setOnMousePressed(e -> this.setEffect(Styles.ButtonInnerShadow));
        this.setOnMouseReleased(e-> this.setEffect(null));
        this.setOnMouseEntered(e -> this.setBackground(Styles.BackgroundButtonHover));
        this.setOnMouseExited(e -> this.setBackground(Styles.BackgroundWhite));
    }

    /**
     * This method applies styling to the button.
     * @param s String to display on the button.
     */
    private void styleIt(String s) {
        this.setText(s);
        this.setFont(Styles.DefaultFont20);
        this.setBorder(Styles.BorderBlack);
        this.setMinSize(120,40);
        this.setMaxSize(120,40);
        this.setPrefSize(120,40);
        this.setBackground(Styles.BackgroundWhite);
        this.addMouseEffects();
    }
}
